### ISSUE TITLE
PHP Fatal error:  Cannot use lexical variable $eventName as a parameter name in google-api-php-client/vendor/guzzlehttp/guzzle/src/Event/Emitter.php on line 48

### ISSUE THREAD

**Issue by sztanpet** [google/google-api-php-client#1068]
Please bump the guzzle version to something not broken on php 7.1
Thank you

**Comment by SerafimArts** [comment]
+1
```
   public function once($eventName, callable $listener, $priority = 0)
    {
        $onceListener = function (
            EventInterface $event,
            $eventName // <======= This line
        ) use (&$onceListener, $eventName, $listener, $priority) {
            $this->removeListener($eventName, $onceListener);
            $listener($event, $eventName, $this);
        };

        $this->on($eventName, $onceListener, $priority);
    }
```

**Comment by acrolink** [comment]
There is a possibility that this is a PHP 7.1 bug since the same error is reported by various PHP applications..

**Comment by SerafimArts** [comment]
This is not a bug of php 7.1. This is bug of very old deprecated guzzle library

**Comment by bshaffer** [comment]
Are you using Guzzle 5.3 on PHP 7.1? As you can see from [composer.json](https://github.com/google/google-api-php-client/blob/master/composer.json#L15), this library supports the current version of guzzle. Guzzle 5.3 is only available for backwards compatibility. 

How is it that Guzzle 5.3 came to be installed instead of Guzzle 6? It could be another package requires guzzle 5.3. Try adding guzzle 6 explicitly to your `composer.json`:

```sh
composer require "guzzlehttp/guzzle:^6.0"
```

**Comment by bshaffer** [comment]
It's also possible your project contains a `composer.lock` file set to the previous version. In this case, run the following command to update all dependencies to the latest versions:

```sh
composer update
```

**Comment by SerafimArts** [comment]
@bshaffer this is side effect of other library. Just close this issue, its not a problem of `google-api-vk-client` ;)

**Comment by bshaffer** [comment]
This has been fixed by bumping the minimum required version of Guzzle to `5.3.1`.

**Comment by ryan-schroeder** [comment]
I was still having this because guzzle was installed globally at 5.3.0; updating the global guzzle (or deleting it) fixed for me, took a while to figure out =)
